### ISSUE TITLE
有关sslvpn在校外服务器上部署的部分似乎已经不可用了

### ISSUE THREAD

**Issue by sunyrain** [thusns/thu-wiki#6]
### Describe the bug

有关sslvpn在校外服务器上部署的部分似乎已经不可用了

### Steps to reproduce

![image](https://github.com/thusns/thu-wiki/assets/89635780/858960ab-7fb9-4ef2-afb0-7ad67831cc40)

**Comment by CoderOJ** [comment]
我这边似乎还是可以用的

**Comment by erbanku** [comment]
@sunyrain 我这边也能正常连接，请问你那边显示什么错误信息呢？
此外，用户名有没有改成`学号`尝试一下呢？

![image](https://github.com/user-attachments/assets/2370bec3-5b7b-4734-9991-12b38914af68)

**Comment by sunyrain** [comment]
五月份的时候似乎有些问题，现在应该可以了，谢谢！
